/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_gamestate_free: (a: number, b: number) => void;
export const gamestate_new: (a: number, b: number) => number;
export const gamestate_add_promiser: (a: number) => void;
export const gamestate_remove_promiser: (a: number, b: number) => void;
export const gamestate_update: (a: number, b: number) => void;
export const gamestate_get_state_data: (a: number) => [number, number];
export const gamestate_get_photons_data: (a: number) => [number, number];
export const gamestate_get_light_map_data: (a: number) => [number, number];
export const gamestate_promiser_count: (a: number) => number;
export const gamestate_tile_map: (a: number) => any;
export const gamestate_make_promiser_think: (a: number, b: number) => void;
export const gamestate_make_promiser_speak: (a: number, b: number, c: number, d: number) => void;
export const gamestate_make_promiser_whisper: (a: number, b: number, c: number, d: number, e: number) => void;
export const gamestate_make_promiser_run: (a: number, b: number) => void;
export const gamestate_place_tile: (a: number, b: number, c: number, d: number, e: number) => void;
export const gamestate_get_tile_at: (a: number, b: number, c: number) => [number, number];
export const gamestate_get_pixel_id: (a: number) => number;
export const gamestate_get_random_promiser_id: (a: number) => number;
export const gamestate_simulate_water: (a: number) => void;
export const init_game: (a: number, b: number) => void;
export const update_game: (a: number) => [number, number];
export const add_promiser: () => void;
export const get_promiser_count: () => number;
export const make_promiser_think: (a: number) => void;
export const make_promiser_speak: (a: number, b: number, c: number) => void;
export const make_promiser_whisper: (a: number, b: number, c: number, d: number) => void;
export const make_promiser_run: (a: number) => void;
export const get_pixel_id: () => number;
export const get_random_promiser_id: () => number;
export const place_tile: (a: number, b: number, c: number, d: number) => void;
export const get_tile_at: (a: number, b: number) => [number, number];
export const simulate_water: () => void;
export const get_photons_data: () => [number, number];
export const get_light_map_data: () => [number, number];
export const main: () => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
